//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Multipagos2V10.ServicioWebMultipagosAmex {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Net;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AmericanExpressSoap11", Namespace="http://adquira.com.mx/amex/definitions")]
    public partial class insPagoAmex : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallinsPagoAmexOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelaPagoAmexOperationCompleted;
        
        private System.Threading.SendOrPostCallback invalidatePagoAmexOperationCompleted;
        
        private System.Threading.SendOrPostCallback echoAmexOperationCompleted;
        
        private System.Threading.SendOrPostCallback genPagoAmexOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public insPagoAmex(string url) {
            this.Url = url;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            //this.Url = global::Multipagos2V10.Properties.Settings.Default.Multipagos2V10_ServicioWebMultipagosAmex_AmericanExpressService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallinsPagoAmexCompletedEventHandler CallinsPagoAmexCompleted;
        
        /// <remarks/>
        public event CancelaPagoAmexCompletedEventHandler CancelaPagoAmexCompleted;
        
        /// <remarks/>
        public event invalidatePagoAmexCompletedEventHandler invalidatePagoAmexCompleted;
        
        /// <remarks/>
        public event echoAmexCompletedEventHandler echoAmexCompleted;
        
        /// <remarks/>
        public event genPagoAmexCompletedEventHandler genPagoAmexCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("insPagoAmexResponse", Namespace="http://adquira.com.mx/amex/schemas")]
        public InsPagoAmexResponseType CallinsPagoAmex([System.Xml.Serialization.XmlElementAttribute(Namespace="http://adquira.com.mx/amex/schemas")] InsPagoAmexRequestType insPagoAmexRequest) {
            object[] results = this.Invoke("CallinsPagoAmex", new object[] {
                        insPagoAmexRequest});
            return ((InsPagoAmexResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CallinsPagoAmexAsync(InsPagoAmexRequestType insPagoAmexRequest) {
            this.CallinsPagoAmexAsync(insPagoAmexRequest, null);
        }
        
        /// <remarks/>
        public void CallinsPagoAmexAsync(InsPagoAmexRequestType insPagoAmexRequest, object userState) {
            if ((this.CallinsPagoAmexOperationCompleted == null)) {
                this.CallinsPagoAmexOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallinsPagoAmexOperationCompleted);
            }
            this.InvokeAsync("CallinsPagoAmex", new object[] {
                        insPagoAmexRequest}, this.CallinsPagoAmexOperationCompleted, userState);
        }
        
        private void OnCallinsPagoAmexOperationCompleted(object arg) {
            if ((this.CallinsPagoAmexCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallinsPagoAmexCompleted(this, new CallinsPagoAmexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CancelaPagoAmexResponse", Namespace="http://adquira.com.mx/amex/schemas")]
        public CancelPagoResponseType CancelaPagoAmex([System.Xml.Serialization.XmlElementAttribute(Namespace="http://adquira.com.mx/amex/schemas")] CancelPagoType CancelaPagoAmexRequest) {
            object[] results = this.Invoke("CancelaPagoAmex", new object[] {
                        CancelaPagoAmexRequest});
            return ((CancelPagoResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CancelaPagoAmexAsync(CancelPagoType CancelaPagoAmexRequest) {
            this.CancelaPagoAmexAsync(CancelaPagoAmexRequest, null);
        }
        
        /// <remarks/>
        public void CancelaPagoAmexAsync(CancelPagoType CancelaPagoAmexRequest, object userState) {
            if ((this.CancelaPagoAmexOperationCompleted == null)) {
                this.CancelaPagoAmexOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelaPagoAmexOperationCompleted);
            }
            this.InvokeAsync("CancelaPagoAmex", new object[] {
                        CancelaPagoAmexRequest}, this.CancelaPagoAmexOperationCompleted, userState);
        }
        
        private void OnCancelaPagoAmexOperationCompleted(object arg) {
            if ((this.CancelaPagoAmexCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelaPagoAmexCompleted(this, new CancelaPagoAmexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("invalidatePagoAmexResponse", Namespace="http://adquira.com.mx/amex/schemas")]
        public InvalidatePagoAmexResponseType invalidatePagoAmex([System.Xml.Serialization.XmlElementAttribute(Namespace="http://adquira.com.mx/amex/schemas")] CancelPagoType invalidatePagoAmexRequest) {
            object[] results = this.Invoke("invalidatePagoAmex", new object[] {
                        invalidatePagoAmexRequest});
            return ((InvalidatePagoAmexResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void invalidatePagoAmexAsync(CancelPagoType invalidatePagoAmexRequest) {
            this.invalidatePagoAmexAsync(invalidatePagoAmexRequest, null);
        }
        
        /// <remarks/>
        public void invalidatePagoAmexAsync(CancelPagoType invalidatePagoAmexRequest, object userState) {
            if ((this.invalidatePagoAmexOperationCompleted == null)) {
                this.invalidatePagoAmexOperationCompleted = new System.Threading.SendOrPostCallback(this.OninvalidatePagoAmexOperationCompleted);
            }
            this.InvokeAsync("invalidatePagoAmex", new object[] {
                        invalidatePagoAmexRequest}, this.invalidatePagoAmexOperationCompleted, userState);
        }
        
        private void OninvalidatePagoAmexOperationCompleted(object arg) {
            if ((this.invalidatePagoAmexCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invalidatePagoAmexCompleted(this, new invalidatePagoAmexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("echoAmexResponse", Namespace="http://adquira.com.mx/amex/schemas")]
        public EchoResponseType echoAmex([System.Xml.Serialization.XmlElementAttribute(Namespace="http://adquira.com.mx/amex/schemas")] string echoAmexRequest) {
            object[] results = this.Invoke("echoAmex", new object[] {
                        echoAmexRequest});
            return ((EchoResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void echoAmexAsync(string echoAmexRequest) {
            this.echoAmexAsync(echoAmexRequest, null);
        }
        
        /// <remarks/>
        public void echoAmexAsync(string echoAmexRequest, object userState) {
            if ((this.echoAmexOperationCompleted == null)) {
                this.echoAmexOperationCompleted = new System.Threading.SendOrPostCallback(this.OnechoAmexOperationCompleted);
            }
            this.InvokeAsync("echoAmex", new object[] {
                        echoAmexRequest}, this.echoAmexOperationCompleted, userState);
        }
        
        private void OnechoAmexOperationCompleted(object arg) {
            if ((this.echoAmexCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.echoAmexCompleted(this, new echoAmexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("genPagoAmexResponse", Namespace="http://adquira.com.mx/amex/schemas")]
        public GenPagoAmexResponseType genPagoAmex([System.Xml.Serialization.XmlElementAttribute(Namespace="http://adquira.com.mx/amex/schemas")] InsPagoAmexRequestType genPagoAmexRequest) {
            object[] results = this.Invoke("genPagoAmex", new object[] {
                        genPagoAmexRequest});
            return ((GenPagoAmexResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void genPagoAmexAsync(InsPagoAmexRequestType genPagoAmexRequest) {
            this.genPagoAmexAsync(genPagoAmexRequest, null);
        }
        
        /// <remarks/>
        public void genPagoAmexAsync(InsPagoAmexRequestType genPagoAmexRequest, object userState) {
            if ((this.genPagoAmexOperationCompleted == null)) {
                this.genPagoAmexOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenPagoAmexOperationCompleted);
            }
            this.InvokeAsync("genPagoAmex", new object[] {
                        genPagoAmexRequest}, this.genPagoAmexOperationCompleted, userState);
        }
        
        private void OngenPagoAmexOperationCompleted(object arg) {
            if ((this.genPagoAmexCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.genPagoAmexCompleted(this, new genPagoAmexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adquira.com.mx/amex/schemas")]
    public partial class InsPagoAmexRequestType {
        
        private string s_transmField;
        
        private string c_referenciaField;
        
        private int val_1Field;
        
        private string t_servicioField;
        
        private int c_curField;
        
        private string t_importeField;
        
        private string titularField;
        
        private string val_3Field;
        
        private string val_4Field;
        
        private string val_5Field;
        
        private string val_6Field;
        
        private string val_11Field;
        
        private string val_12Field;
        
        private int clave_entidadField;
        
        private int val_19Field;
        
        private System.Nullable<int> val_20Field;
        
        private TarjetaDigitadaType tarjetaDigitadaField;
        
        private TarjetaDeslizadaType tarjetaDeslizadaField;
        
        private TarjetaChipType tarjetaChipField;
        
        private ValidacionAVSType validacionAVSField;
        
        private string finalStatusField;
        
        private string extraDataField;
        
        /// <remarks/>
        public string s_transm {
            get {
                return this.s_transmField;
            }
            set {
                this.s_transmField = value;
            }
        }
        
        /// <remarks/>
        public string c_referencia {
            get {
                return this.c_referenciaField;
            }
            set {
                this.c_referenciaField = value;
            }
        }
        
        /// <remarks/>
        public int val_1 {
            get {
                return this.val_1Field;
            }
            set {
                this.val_1Field = value;
            }
        }
        
        /// <remarks/>
        public string t_servicio {
            get {
                return this.t_servicioField;
            }
            set {
                this.t_servicioField = value;
            }
        }
        
        /// <remarks/>
        public int c_cur {
            get {
                return this.c_curField;
            }
            set {
                this.c_curField = value;
            }
        }
        
        /// <remarks/>
        public string t_importe {
            get {
                return this.t_importeField;
            }
            set {
                this.t_importeField = value;
            }
        }
        
        /// <remarks/>
        public string titular {
            get {
                return this.titularField;
            }
            set {
                this.titularField = value;
            }
        }
        
        /// <remarks/>
        public string val_3 {
            get {
                return this.val_3Field;
            }
            set {
                this.val_3Field = value;
            }
        }
        
        /// <remarks/>
        public string val_4 {
            get {
                return this.val_4Field;
            }
            set {
                this.val_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string val_5 {
            get {
                return this.val_5Field;
            }
            set {
                this.val_5Field = value;
            }
        }
        
        /// <remarks/>
        public string val_6 {
            get {
                return this.val_6Field;
            }
            set {
                this.val_6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string val_11 {
            get {
                return this.val_11Field;
            }
            set {
                this.val_11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string val_12 {
            get {
                return this.val_12Field;
            }
            set {
                this.val_12Field = value;
            }
        }
        
        /// <remarks/>
        public int clave_entidad {
            get {
                return this.clave_entidadField;
            }
            set {
                this.clave_entidadField = value;
            }
        }
        
        /// <remarks/>
        public int val_19 {
            get {
                return this.val_19Field;
            }
            set {
                this.val_19Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> val_20 {
            get {
                return this.val_20Field;
            }
            set {
                this.val_20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TarjetaDigitadaType tarjetaDigitada {
            get {
                return this.tarjetaDigitadaField;
            }
            set {
                this.tarjetaDigitadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TarjetaDeslizadaType tarjetaDeslizada {
            get {
                return this.tarjetaDeslizadaField;
            }
            set {
                this.tarjetaDeslizadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TarjetaChipType tarjetaChip {
            get {
                return this.tarjetaChipField;
            }
            set {
                this.tarjetaChipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ValidacionAVSType validacionAVS {
            get {
                return this.validacionAVSField;
            }
            set {
                this.validacionAVSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string finalStatus {
            get {
                return this.finalStatusField;
            }
            set {
                this.finalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string extraData {
            get {
                return this.extraDataField;
            }
            set {
                this.extraDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adquira.com.mx/amex/schemas")]
    public partial class TarjetaDigitadaType {
        
        private int operationEnvironmentField;
        
        private string cardHolderPresentField;
        
        private bool cardPresentField;
        
        private CompraRemotaType compraRemotaClienteField;
        
        /// <remarks/>
        public int operationEnvironment {
            get {
                return this.operationEnvironmentField;
            }
            set {
                this.operationEnvironmentField = value;
            }
        }
        
        /// <remarks/>
        public string cardHolderPresent {
            get {
                return this.cardHolderPresentField;
            }
            set {
                this.cardHolderPresentField = value;
            }
        }
        
        /// <remarks/>
        public bool cardPresent {
            get {
                return this.cardPresentField;
            }
            set {
                this.cardPresentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompraRemotaType compraRemotaCliente {
            get {
                return this.compraRemotaClienteField;
            }
            set {
                this.compraRemotaClienteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adquira.com.mx/amex/schemas")]
    public partial class CompraRemotaType {
        
        private string browserField;
        
        private string shippingField;
        
        private string productIdField;
        
        private string ipClienteField;
        
        /// <remarks/>
        public string browser {
            get {
                return this.browserField;
            }
            set {
                this.browserField = value;
            }
        }
        
        /// <remarks/>
        public string shipping {
            get {
                return this.shippingField;
            }
            set {
                this.shippingField = value;
            }
        }
        
        /// <remarks/>
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public string ipCliente {
            get {
                return this.ipClienteField;
            }
            set {
                this.ipClienteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adquira.com.mx/amex/schemas")]
    public partial class GenPagoAmexResponseType {
        
        private string autorizacionField;
        
        private string criptogramaField;
        
        private string mensajeField;
        
        private int codigoRespuestaField;
        
        private string xmlPagareField;
        
        /// <remarks/>
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
            }
        }
        
        /// <remarks/>
        public string criptograma {
            get {
                return this.criptogramaField;
            }
            set {
                this.criptogramaField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public int codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public string xmlPagare {
            get {
                return this.xmlPagareField;
            }
            set {
                this.xmlPagareField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adquira.com.mx/amex/schemas")]
    public partial class EchoResponseType {
        
        private string echoField;
        
        private string actionCodeField;
        
        /// <remarks/>
        public string echo {
            get {
                return this.echoField;
            }
            set {
                this.echoField = value;
            }
        }
        
        /// <remarks/>
        public string actionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adquira.com.mx/amex/schemas")]
    public partial class InvalidatePagoAmexResponseType {
        
        private string t_servicioField;
        
        private int clave_entidadField;
        
        private int val_1Field;
        
        private int c_curField;
        
        private int codigoRespuestaField;
        
        private string mensajeField;
        
        private string systemTraceNumberField;
        
        private string transactionIDField;
        
        private string transactionAmountField;
        
        private string consecutivoPagoField;
        
        private string authorizationCodeField;
        
        private string nombreComercioField;
        
        private string direccionComercioField;
        
        private string afiliacionField;
        
        private string horaTransaccionField;
        
        private string vencimientoField;
        
        private string montoField;
        
        private string titularField;
        
        private string tdcField;
        
        private string xmlPagareField;
        
        /// <remarks/>
        public string t_servicio {
            get {
                return this.t_servicioField;
            }
            set {
                this.t_servicioField = value;
            }
        }
        
        /// <remarks/>
        public int clave_entidad {
            get {
                return this.clave_entidadField;
            }
            set {
                this.clave_entidadField = value;
            }
        }
        
        /// <remarks/>
        public int val_1 {
            get {
                return this.val_1Field;
            }
            set {
                this.val_1Field = value;
            }
        }
        
        /// <remarks/>
        public int c_cur {
            get {
                return this.c_curField;
            }
            set {
                this.c_curField = value;
            }
        }
        
        /// <remarks/>
        public int codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string systemTraceNumber {
            get {
                return this.systemTraceNumberField;
            }
            set {
                this.systemTraceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string transactionAmount {
            get {
                return this.transactionAmountField;
            }
            set {
                this.transactionAmountField = value;
            }
        }
        
        /// <remarks/>
        public string consecutivoPago {
            get {
                return this.consecutivoPagoField;
            }
            set {
                this.consecutivoPagoField = value;
            }
        }
        
        /// <remarks/>
        public string authorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string nombreComercio {
            get {
                return this.nombreComercioField;
            }
            set {
                this.nombreComercioField = value;
            }
        }
        
        /// <remarks/>
        public string direccionComercio {
            get {
                return this.direccionComercioField;
            }
            set {
                this.direccionComercioField = value;
            }
        }
        
        /// <remarks/>
        public string afiliacion {
            get {
                return this.afiliacionField;
            }
            set {
                this.afiliacionField = value;
            }
        }
        
        /// <remarks/>
        public string horaTransaccion {
            get {
                return this.horaTransaccionField;
            }
            set {
                this.horaTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string vencimiento {
            get {
                return this.vencimientoField;
            }
            set {
                this.vencimientoField = value;
            }
        }
        
        /// <remarks/>
        public string monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string titular {
            get {
                return this.titularField;
            }
            set {
                this.titularField = value;
            }
        }
        
        /// <remarks/>
        public string tdc {
            get {
                return this.tdcField;
            }
            set {
                this.tdcField = value;
            }
        }
        
        /// <remarks/>
        public string xmlPagare {
            get {
                return this.xmlPagareField;
            }
            set {
                this.xmlPagareField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adquira.com.mx/amex/schemas")]
    public partial class CancelPagoResponseType {
        
        private string t_servicioField;
        
        private int clave_entidadField;
        
        private int val_1Field;
        
        private int c_curField;
        
        private int codigoRespuestaField;
        
        private string mensajeField;
        
        private string systemTraceNumberField;
        
        private string transactionIDField;
        
        private string transactionAmountField;
        
        private string consecutivoPagoField;
        
        private string authorizationCodeField;
        
        private string nombreComercioField;
        
        private string direccionComercioField;
        
        private string afiliacionField;
        
        private string horaTransaccionField;
        
        private string vencimientoField;
        
        private string montoField;
        
        private string titularField;
        
        private string tdcField;
        
        /// <remarks/>
        public string t_servicio {
            get {
                return this.t_servicioField;
            }
            set {
                this.t_servicioField = value;
            }
        }
        
        /// <remarks/>
        public int clave_entidad {
            get {
                return this.clave_entidadField;
            }
            set {
                this.clave_entidadField = value;
            }
        }
        
        /// <remarks/>
        public int val_1 {
            get {
                return this.val_1Field;
            }
            set {
                this.val_1Field = value;
            }
        }
        
        /// <remarks/>
        public int c_cur {
            get {
                return this.c_curField;
            }
            set {
                this.c_curField = value;
            }
        }
        
        /// <remarks/>
        public int codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string systemTraceNumber {
            get {
                return this.systemTraceNumberField;
            }
            set {
                this.systemTraceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string transactionAmount {
            get {
                return this.transactionAmountField;
            }
            set {
                this.transactionAmountField = value;
            }
        }
        
        /// <remarks/>
        public string consecutivoPago {
            get {
                return this.consecutivoPagoField;
            }
            set {
                this.consecutivoPagoField = value;
            }
        }
        
        /// <remarks/>
        public string authorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string nombreComercio {
            get {
                return this.nombreComercioField;
            }
            set {
                this.nombreComercioField = value;
            }
        }
        
        /// <remarks/>
        public string direccionComercio {
            get {
                return this.direccionComercioField;
            }
            set {
                this.direccionComercioField = value;
            }
        }
        
        /// <remarks/>
        public string afiliacion {
            get {
                return this.afiliacionField;
            }
            set {
                this.afiliacionField = value;
            }
        }
        
        /// <remarks/>
        public string horaTransaccion {
            get {
                return this.horaTransaccionField;
            }
            set {
                this.horaTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string vencimiento {
            get {
                return this.vencimientoField;
            }
            set {
                this.vencimientoField = value;
            }
        }
        
        /// <remarks/>
        public string monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string titular {
            get {
                return this.titularField;
            }
            set {
                this.titularField = value;
            }
        }
        
        /// <remarks/>
        public string tdc {
            get {
                return this.tdcField;
            }
            set {
                this.tdcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adquira.com.mx/amex/schemas")]
    public partial class CancelPagoType {
        
        private string t_servicioField;
        
        private int clave_entidadField;
        
        private int val_1Field;
        
        private int c_curField;
        
        private string cd_origenField;
        
        private int nu_conpgoField;
        
        private string cd_autpgoField;
        
        /// <remarks/>
        public string t_servicio {
            get {
                return this.t_servicioField;
            }
            set {
                this.t_servicioField = value;
            }
        }
        
        /// <remarks/>
        public int clave_entidad {
            get {
                return this.clave_entidadField;
            }
            set {
                this.clave_entidadField = value;
            }
        }
        
        /// <remarks/>
        public int val_1 {
            get {
                return this.val_1Field;
            }
            set {
                this.val_1Field = value;
            }
        }
        
        /// <remarks/>
        public int c_cur {
            get {
                return this.c_curField;
            }
            set {
                this.c_curField = value;
            }
        }
        
        /// <remarks/>
        public string cd_origen {
            get {
                return this.cd_origenField;
            }
            set {
                this.cd_origenField = value;
            }
        }
        
        /// <remarks/>
        public int nu_conpgo {
            get {
                return this.nu_conpgoField;
            }
            set {
                this.nu_conpgoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cd_autpgo {
            get {
                return this.cd_autpgoField;
            }
            set {
                this.cd_autpgoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adquira.com.mx/amex/schemas")]
    public partial class InsPagoAmexResponseType {
        
        private string t_servicioField;
        
        private int clave_entidadField;
        
        private int val_1Field;
        
        private int c_curField;
        
        private int codigoRespuestaField;
        
        private string mensajeField;
        
        private string systemTraceNumberField;
        
        private string transactionIDField;
        
        private string transactionAmountField;
        
        private string consecutivoPagoField;
        
        private string authorizationCodeField;
        
        private string nombreComercioField;
        
        private string direccionComercioField;
        
        private string afiliacionField;
        
        private string horaTransaccionField;
        
        private string integratedCircuitField;
        
        private string aidField;
        
        private string firmaField;
        
        /// <remarks/>
        public string t_servicio {
            get {
                return this.t_servicioField;
            }
            set {
                this.t_servicioField = value;
            }
        }
        
        /// <remarks/>
        public int clave_entidad {
            get {
                return this.clave_entidadField;
            }
            set {
                this.clave_entidadField = value;
            }
        }
        
        /// <remarks/>
        public int val_1 {
            get {
                return this.val_1Field;
            }
            set {
                this.val_1Field = value;
            }
        }
        
        /// <remarks/>
        public int c_cur {
            get {
                return this.c_curField;
            }
            set {
                this.c_curField = value;
            }
        }
        
        /// <remarks/>
        public int codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string systemTraceNumber {
            get {
                return this.systemTraceNumberField;
            }
            set {
                this.systemTraceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string transactionAmount {
            get {
                return this.transactionAmountField;
            }
            set {
                this.transactionAmountField = value;
            }
        }
        
        /// <remarks/>
        public string consecutivoPago {
            get {
                return this.consecutivoPagoField;
            }
            set {
                this.consecutivoPagoField = value;
            }
        }
        
        /// <remarks/>
        public string authorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string nombreComercio {
            get {
                return this.nombreComercioField;
            }
            set {
                this.nombreComercioField = value;
            }
        }
        
        /// <remarks/>
        public string direccionComercio {
            get {
                return this.direccionComercioField;
            }
            set {
                this.direccionComercioField = value;
            }
        }
        
        /// <remarks/>
        public string afiliacion {
            get {
                return this.afiliacionField;
            }
            set {
                this.afiliacionField = value;
            }
        }
        
        /// <remarks/>
        public string horaTransaccion {
            get {
                return this.horaTransaccionField;
            }
            set {
                this.horaTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string integratedCircuit {
            get {
                return this.integratedCircuitField;
            }
            set {
                this.integratedCircuitField = value;
            }
        }
        
        /// <remarks/>
        public string aid {
            get {
                return this.aidField;
            }
            set {
                this.aidField = value;
            }
        }
        
        /// <remarks/>
        public string firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adquira.com.mx/amex/schemas")]
    public partial class EnvioCompraType {
        
        private string codigoPostalDestinatarioField;
        
        private string direccionDestinatarioField;
        
        private string nombreDestinatarioField;
        
        private string apellidosDestinatarioField;
        
        private string telefonoDestinatarioField;
        
        private string paisDestinatarioField;
        
        /// <remarks/>
        public string codigoPostalDestinatario {
            get {
                return this.codigoPostalDestinatarioField;
            }
            set {
                this.codigoPostalDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string direccionDestinatario {
            get {
                return this.direccionDestinatarioField;
            }
            set {
                this.direccionDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string nombreDestinatario {
            get {
                return this.nombreDestinatarioField;
            }
            set {
                this.nombreDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string apellidosDestinatario {
            get {
                return this.apellidosDestinatarioField;
            }
            set {
                this.apellidosDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string telefonoDestinatario {
            get {
                return this.telefonoDestinatarioField;
            }
            set {
                this.telefonoDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string paisDestinatario {
            get {
                return this.paisDestinatarioField;
            }
            set {
                this.paisDestinatarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adquira.com.mx/amex/schemas")]
    public partial class ValidacionAVSType {
        
        private string nombreTitularField;
        
        private string apellidosTitularField;
        
        private string codigoPostalField;
        
        private string direccionField;
        
        private EnvioCompraType datosEnvioField;
        
        /// <remarks/>
        public string nombreTitular {
            get {
                return this.nombreTitularField;
            }
            set {
                this.nombreTitularField = value;
            }
        }
        
        /// <remarks/>
        public string apellidosTitular {
            get {
                return this.apellidosTitularField;
            }
            set {
                this.apellidosTitularField = value;
            }
        }
        
        /// <remarks/>
        public string codigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                this.codigoPostalField = value;
            }
        }
        
        /// <remarks/>
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EnvioCompraType datosEnvio {
            get {
                return this.datosEnvioField;
            }
            set {
                this.datosEnvioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adquira.com.mx/amex/schemas")]
    public partial class TarjetaChipType {
        
        private int operationEnvironmentField;
        
        private string applicationCryptogramField;
        
        private string issuerApplicationDataField;
        
        private string unpredictableNumberField;
        
        private string applicationTransactionCounterField;
        
        private string terminalVerificationResultField;
        
        private string transactionDateField;
        
        private string transactionTypeField;
        
        private string amountAuthorizedField;
        
        private string transactionCurrencyCodeField;
        
        private string terminalCountryCodeField;
        
        private string applicationInterchangeProfileField;
        
        private string amountOtherField;
        
        private string applicationPANSequenceField;
        
        private string cryptogramInformationDataField;

        // snr
        private string track2Field;

        public string track2
        {
            get
            {
                return this.track2Field;
            }
            set
            {
                this.track2Field = value;
            }
        }
        // snr
        /// <remarks/>
        public int operationEnvironment {
            get {
                return this.operationEnvironmentField;
            }
            set {
                this.operationEnvironmentField = value;
            }
        }
        
        /// <remarks/>
        public string applicationCryptogram {
            get {
                return this.applicationCryptogramField;
            }
            set {
                this.applicationCryptogramField = value;
            }
        }
        
        /// <remarks/>
        public string issuerApplicationData {
            get {
                return this.issuerApplicationDataField;
            }
            set {
                this.issuerApplicationDataField = value;
            }
        }
        
        /// <remarks/>
        public string unpredictableNumber {
            get {
                return this.unpredictableNumberField;
            }
            set {
                this.unpredictableNumberField = value;
            }
        }
        
        /// <remarks/>
        public string applicationTransactionCounter {
            get {
                return this.applicationTransactionCounterField;
            }
            set {
                this.applicationTransactionCounterField = value;
            }
        }
        
        /// <remarks/>
        public string terminalVerificationResult {
            get {
                return this.terminalVerificationResultField;
            }
            set {
                this.terminalVerificationResultField = value;
            }
        }
        
        /// <remarks/>
        public string transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        public string transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string amountAuthorized {
            get {
                return this.amountAuthorizedField;
            }
            set {
                this.amountAuthorizedField = value;
            }
        }
        
        /// <remarks/>
        public string transactionCurrencyCode {
            get {
                return this.transactionCurrencyCodeField;
            }
            set {
                this.transactionCurrencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string terminalCountryCode {
            get {
                return this.terminalCountryCodeField;
            }
            set {
                this.terminalCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string applicationInterchangeProfile {
            get {
                return this.applicationInterchangeProfileField;
            }
            set {
                this.applicationInterchangeProfileField = value;
            }
        }
        
        /// <remarks/>
        public string amountOther {
            get {
                return this.amountOtherField;
            }
            set {
                this.amountOtherField = value;
            }
        }
        
        /// <remarks/>
        public string applicationPANSequence {
            get {
                return this.applicationPANSequenceField;
            }
            set {
                this.applicationPANSequenceField = value;
            }
        }
        
        /// <remarks/>
        public string cryptogramInformationData {
            get {
                return this.cryptogramInformationDataField;
            }
            set {
                this.cryptogramInformationDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adquira.com.mx/amex/schemas")]
    public partial class TarjetaDeslizadaType {
        
        private string track1Field;
        
        private string track2Field;
        
        private int operationEnvironmentField;
        
        /// <remarks/>
        public string track1 {
            get {
                return this.track1Field;
            }
            set {
                this.track1Field = value;
            }
        }
        
        /// <remarks/>
        public string track2 {
            get {
                return this.track2Field;
            }
            set {
                this.track2Field = value;
            }
        }
        
        /// <remarks/>
        public int operationEnvironment {
            get {
                return this.operationEnvironmentField;
            }
            set {
                this.operationEnvironmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CallinsPagoAmexCompletedEventHandler(object sender, CallinsPagoAmexCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallinsPagoAmexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallinsPagoAmexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InsPagoAmexResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InsPagoAmexResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CancelaPagoAmexCompletedEventHandler(object sender, CancelaPagoAmexCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelaPagoAmexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelaPagoAmexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelPagoResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelPagoResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void invalidatePagoAmexCompletedEventHandler(object sender, invalidatePagoAmexCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invalidatePagoAmexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal invalidatePagoAmexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InvalidatePagoAmexResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InvalidatePagoAmexResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void echoAmexCompletedEventHandler(object sender, echoAmexCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class echoAmexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal echoAmexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EchoResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EchoResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void genPagoAmexCompletedEventHandler(object sender, genPagoAmexCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class genPagoAmexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal genPagoAmexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GenPagoAmexResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GenPagoAmexResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591