//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Multipagos2V10.ServiciosWebMultipagosPuntos5_1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProcesadorPuntosFullSoapBinding", Namespace="http://ws.puntos.cifrada.interred.adquira.com.mx")]
    public partial class ProcesadorPuntosFull : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback compraOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback validaOperationCompleted;
        
        private System.Threading.SendOrPostCallback compraCEOperationCompleted;
        
        private System.Threading.SendOrPostCallback compraCEVOperationCompleted;
        
        private System.Threading.SendOrPostCallback compraCE10OperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaCEOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelacionCEOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelacionCEVOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBinesDeLealtadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProcesadorPuntosFull() {
            this.Url = global::Multipagos2V10.Properties.Settings.Default.Multipagos2V10_ServiciosWebMultipagosPuntos5_1_ProcesadorPuntosFull;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultaCompletedEventHandler consultaCompleted;
        
        /// <remarks/>
        public event compraCompletedEventHandler compraCompleted;
        
        /// <remarks/>
        public event cancelacionCompletedEventHandler cancelacionCompleted;
        
        /// <remarks/>
        public event validaCompletedEventHandler validaCompleted;
        
        /// <remarks/>
        public event compraCECompletedEventHandler compraCECompleted;
        
        /// <remarks/>
        public event compraCEVCompletedEventHandler compraCEVCompleted;
        
        /// <remarks/>
        public event compraCE10CompletedEventHandler compraCE10Completed;
        
        /// <remarks/>
        public event consultaCECompletedEventHandler consultaCECompleted;
        
        /// <remarks/>
        public event cancelacionCECompletedEventHandler cancelacionCECompleted;
        
        /// <remarks/>
        public event cancelacionCEVCompletedEventHandler cancelacionCEVCompleted;
        
        /// <remarks/>
        public event getBinesDeLealtadCompletedEventHandler getBinesDeLealtadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", ResponseNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultaReturn")]
        public string consulta(
                    int val_1, 
                    int val_2, 
                    int val_3, 
                    int val_4, 
                    string val_5, 
                    string val_6, 
                    string val_7, 
                    string val_8, 
                    string val_9, 
                    string val_10, 
                    string val_11, 
                    string val_12, 
                    string val_13, 
                    string val_14, 
                    string val_15, 
                    int fallback, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19) {
            object[] results = this.Invoke("consulta", new object[] {
                        val_1,
                        val_2,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        val_7,
                        val_8,
                        val_9,
                        val_10,
                        val_11,
                        val_12,
                        val_13,
                        val_14,
                        val_15,
                        fallback,
                        val_16,
                        val_17,
                        val_18,
                        val_19});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaAsync(
                    int val_1, 
                    int val_2, 
                    int val_3, 
                    int val_4, 
                    string val_5, 
                    string val_6, 
                    string val_7, 
                    string val_8, 
                    string val_9, 
                    string val_10, 
                    string val_11, 
                    string val_12, 
                    string val_13, 
                    string val_14, 
                    string val_15, 
                    int fallback, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19) {
            this.consultaAsync(val_1, val_2, val_3, val_4, val_5, val_6, val_7, val_8, val_9, val_10, val_11, val_12, val_13, val_14, val_15, fallback, val_16, val_17, val_18, val_19, null);
        }
        
        /// <remarks/>
        public void consultaAsync(
                    int val_1, 
                    int val_2, 
                    int val_3, 
                    int val_4, 
                    string val_5, 
                    string val_6, 
                    string val_7, 
                    string val_8, 
                    string val_9, 
                    string val_10, 
                    string val_11, 
                    string val_12, 
                    string val_13, 
                    string val_14, 
                    string val_15, 
                    int fallback, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    object userState) {
            if ((this.consultaOperationCompleted == null)) {
                this.consultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaOperationCompleted);
            }
            this.InvokeAsync("consulta", new object[] {
                        val_1,
                        val_2,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        val_7,
                        val_8,
                        val_9,
                        val_10,
                        val_11,
                        val_12,
                        val_13,
                        val_14,
                        val_15,
                        fallback,
                        val_16,
                        val_17,
                        val_18,
                        val_19}, this.consultaOperationCompleted, userState);
        }
        
        private void OnconsultaOperationCompleted(object arg) {
            if ((this.consultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaCompleted(this, new consultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", ResponseNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("compraReturn")]
        public string compra(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    string val_11, 
                    string val_12, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    int fallback, 
                    string terminal, 
                    int puntos) {
            object[] results = this.Invoke("compra", new object[] {
                        s_transm,
                        c_referencia,
                        val_1,
                        t_servicio,
                        c_cur,
                        t_importe,
                        tarjetahabiente,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        val_11,
                        val_12,
                        clave_entidad,
                        val_16,
                        val_17,
                        val_18,
                        val_19,
                        val_20,
                        email_admin,
                        accion,
                        TAG5F34,
                        TAGSEMV,
                        sFlag,
                        TAG9F26,
                        TAG9F27,
                        fallback,
                        terminal,
                        puntos});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void compraAsync(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    string val_11, 
                    string val_12, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    int fallback, 
                    string terminal, 
                    int puntos) {
            this.compraAsync(s_transm, c_referencia, val_1, t_servicio, c_cur, t_importe, tarjetahabiente, val_3, val_4, val_5, val_6, val_11, val_12, clave_entidad, val_16, val_17, val_18, val_19, val_20, email_admin, accion, TAG5F34, TAGSEMV, sFlag, TAG9F26, TAG9F27, fallback, terminal, puntos, null);
        }
        
        /// <remarks/>
        public void compraAsync(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    string val_11, 
                    string val_12, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    int fallback, 
                    string terminal, 
                    int puntos, 
                    object userState) {
            if ((this.compraOperationCompleted == null)) {
                this.compraOperationCompleted = new System.Threading.SendOrPostCallback(this.OncompraOperationCompleted);
            }
            this.InvokeAsync("compra", new object[] {
                        s_transm,
                        c_referencia,
                        val_1,
                        t_servicio,
                        c_cur,
                        t_importe,
                        tarjetahabiente,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        val_11,
                        val_12,
                        clave_entidad,
                        val_16,
                        val_17,
                        val_18,
                        val_19,
                        val_20,
                        email_admin,
                        accion,
                        TAG5F34,
                        TAGSEMV,
                        sFlag,
                        TAG9F26,
                        TAG9F27,
                        fallback,
                        terminal,
                        puntos}, this.compraOperationCompleted, userState);
        }
        
        private void OncompraOperationCompleted(object arg) {
            if ((this.compraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.compraCompleted(this, new compraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", ResponseNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("cancelacionReturn")]
        public string cancelacion(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    string cd_autorizacion, 
                    string terminal) {
            object[] results = this.Invoke("cancelacion", new object[] {
                        s_transm,
                        c_referencia,
                        val_1,
                        t_servicio,
                        c_cur,
                        t_importe,
                        tarjetahabiente,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        clave_entidad,
                        val_16,
                        val_17,
                        val_18,
                        val_19,
                        val_20,
                        email_admin,
                        accion,
                        TAG5F34,
                        TAGSEMV,
                        sFlag,
                        TAG9F26,
                        TAG9F27,
                        cd_autorizacion,
                        terminal});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cancelacionAsync(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    string cd_autorizacion, 
                    string terminal) {
            this.cancelacionAsync(s_transm, c_referencia, val_1, t_servicio, c_cur, t_importe, tarjetahabiente, val_3, val_4, val_5, val_6, clave_entidad, val_16, val_17, val_18, val_19, val_20, email_admin, accion, TAG5F34, TAGSEMV, sFlag, TAG9F26, TAG9F27, cd_autorizacion, terminal, null);
        }
        
        /// <remarks/>
        public void cancelacionAsync(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    string cd_autorizacion, 
                    string terminal, 
                    object userState) {
            if ((this.cancelacionOperationCompleted == null)) {
                this.cancelacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelacionOperationCompleted);
            }
            this.InvokeAsync("cancelacion", new object[] {
                        s_transm,
                        c_referencia,
                        val_1,
                        t_servicio,
                        c_cur,
                        t_importe,
                        tarjetahabiente,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        clave_entidad,
                        val_16,
                        val_17,
                        val_18,
                        val_19,
                        val_20,
                        email_admin,
                        accion,
                        TAG5F34,
                        TAGSEMV,
                        sFlag,
                        TAG9F26,
                        TAG9F27,
                        cd_autorizacion,
                        terminal}, this.cancelacionOperationCompleted, userState);
        }
        
        private void OncancelacionOperationCompleted(object arg) {
            if ((this.cancelacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelacionCompleted(this, new cancelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", ResponseNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("validaReturn")]
        public string valida(string cdEntidad, string val_3, string email, string accion) {
            object[] results = this.Invoke("valida", new object[] {
                        cdEntidad,
                        val_3,
                        email,
                        accion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void validaAsync(string cdEntidad, string val_3, string email, string accion) {
            this.validaAsync(cdEntidad, val_3, email, accion, null);
        }
        
        /// <remarks/>
        public void validaAsync(string cdEntidad, string val_3, string email, string accion, object userState) {
            if ((this.validaOperationCompleted == null)) {
                this.validaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidaOperationCompleted);
            }
            this.InvokeAsync("valida", new object[] {
                        cdEntidad,
                        val_3,
                        email,
                        accion}, this.validaOperationCompleted, userState);
        }
        
        private void OnvalidaOperationCompleted(object arg) {
            if ((this.validaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validaCompleted(this, new validaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", ResponseNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("compraCEReturn")]
        public string compraCE(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    string val_11, 
                    string val_12, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    int fallback, 
                    string terminal, 
                    int puntos) {
            object[] results = this.Invoke("compraCE", new object[] {
                        s_transm,
                        c_referencia,
                        val_1,
                        t_servicio,
                        c_cur,
                        t_importe,
                        tarjetahabiente,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        val_11,
                        val_12,
                        clave_entidad,
                        val_16,
                        val_17,
                        val_18,
                        val_19,
                        val_20,
                        email_admin,
                        accion,
                        TAG5F34,
                        TAGSEMV,
                        sFlag,
                        TAG9F26,
                        TAG9F27,
                        fallback,
                        terminal,
                        puntos});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void compraCEAsync(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    string val_11, 
                    string val_12, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    int fallback, 
                    string terminal, 
                    int puntos) {
            this.compraCEAsync(s_transm, c_referencia, val_1, t_servicio, c_cur, t_importe, tarjetahabiente, val_3, val_4, val_5, val_6, val_11, val_12, clave_entidad, val_16, val_17, val_18, val_19, val_20, email_admin, accion, TAG5F34, TAGSEMV, sFlag, TAG9F26, TAG9F27, fallback, terminal, puntos, null);
        }
        
        /// <remarks/>
        public void compraCEAsync(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    string val_11, 
                    string val_12, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    int fallback, 
                    string terminal, 
                    int puntos, 
                    object userState) {
            if ((this.compraCEOperationCompleted == null)) {
                this.compraCEOperationCompleted = new System.Threading.SendOrPostCallback(this.OncompraCEOperationCompleted);
            }
            this.InvokeAsync("compraCE", new object[] {
                        s_transm,
                        c_referencia,
                        val_1,
                        t_servicio,
                        c_cur,
                        t_importe,
                        tarjetahabiente,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        val_11,
                        val_12,
                        clave_entidad,
                        val_16,
                        val_17,
                        val_18,
                        val_19,
                        val_20,
                        email_admin,
                        accion,
                        TAG5F34,
                        TAGSEMV,
                        sFlag,
                        TAG9F26,
                        TAG9F27,
                        fallback,
                        terminal,
                        puntos}, this.compraCEOperationCompleted, userState);
        }
        
        private void OncompraCEOperationCompleted(object arg) {
            if ((this.compraCECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.compraCECompleted(this, new compraCECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", ResponseNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("compraCEVReturn")]
        public string compraCEV(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    string val_11, 
                    string val_12, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    int fallback, 
                    string terminal, 
                    int puntos, 
                    string version) {
            object[] results = this.Invoke("compraCEV", new object[] {
                        s_transm,
                        c_referencia,
                        val_1,
                        t_servicio,
                        c_cur,
                        t_importe,
                        tarjetahabiente,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        val_11,
                        val_12,
                        clave_entidad,
                        val_16,
                        val_17,
                        val_18,
                        val_19,
                        val_20,
                        email_admin,
                        accion,
                        TAG5F34,
                        TAGSEMV,
                        sFlag,
                        TAG9F26,
                        TAG9F27,
                        fallback,
                        terminal,
                        puntos,
                        version});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void compraCEVAsync(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    string val_11, 
                    string val_12, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    int fallback, 
                    string terminal, 
                    int puntos, 
                    string version) {
            this.compraCEVAsync(s_transm, c_referencia, val_1, t_servicio, c_cur, t_importe, tarjetahabiente, val_3, val_4, val_5, val_6, val_11, val_12, clave_entidad, val_16, val_17, val_18, val_19, val_20, email_admin, accion, TAG5F34, TAGSEMV, sFlag, TAG9F26, TAG9F27, fallback, terminal, puntos, version, null);
        }
        
        /// <remarks/>
        public void compraCEVAsync(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    string val_11, 
                    string val_12, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    int fallback, 
                    string terminal, 
                    int puntos, 
                    string version, 
                    object userState) {
            if ((this.compraCEVOperationCompleted == null)) {
                this.compraCEVOperationCompleted = new System.Threading.SendOrPostCallback(this.OncompraCEVOperationCompleted);
            }
            this.InvokeAsync("compraCEV", new object[] {
                        s_transm,
                        c_referencia,
                        val_1,
                        t_servicio,
                        c_cur,
                        t_importe,
                        tarjetahabiente,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        val_11,
                        val_12,
                        clave_entidad,
                        val_16,
                        val_17,
                        val_18,
                        val_19,
                        val_20,
                        email_admin,
                        accion,
                        TAG5F34,
                        TAGSEMV,
                        sFlag,
                        TAG9F26,
                        TAG9F27,
                        fallback,
                        terminal,
                        puntos,
                        version}, this.compraCEVOperationCompleted, userState);
        }
        
        private void OncompraCEVOperationCompleted(object arg) {
            if ((this.compraCEVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.compraCEVCompleted(this, new compraCEVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", ResponseNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("compraCE10Return")]
        public string compraCE10(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    string val_11, 
                    string val_12, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    int fallback, 
                    string terminal, 
                    int puntos, 
                    string version, 
                    string aid, 
                    string applabel) {
            object[] results = this.Invoke("compraCE10", new object[] {
                        s_transm,
                        c_referencia,
                        val_1,
                        t_servicio,
                        c_cur,
                        t_importe,
                        tarjetahabiente,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        val_11,
                        val_12,
                        clave_entidad,
                        val_16,
                        val_17,
                        val_18,
                        val_19,
                        val_20,
                        email_admin,
                        accion,
                        TAG5F34,
                        TAGSEMV,
                        sFlag,
                        TAG9F26,
                        TAG9F27,
                        fallback,
                        terminal,
                        puntos,
                        version,
                        aid,
                        applabel});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void compraCE10Async(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    string val_11, 
                    string val_12, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    int fallback, 
                    string terminal, 
                    int puntos, 
                    string version, 
                    string aid, 
                    string applabel) {
            this.compraCE10Async(s_transm, c_referencia, val_1, t_servicio, c_cur, t_importe, tarjetahabiente, val_3, val_4, val_5, val_6, val_11, val_12, clave_entidad, val_16, val_17, val_18, val_19, val_20, email_admin, accion, TAG5F34, TAGSEMV, sFlag, TAG9F26, TAG9F27, fallback, terminal, puntos, version, aid, applabel, null);
        }
        
        /// <remarks/>
        public void compraCE10Async(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    string val_11, 
                    string val_12, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    int fallback, 
                    string terminal, 
                    int puntos, 
                    string version, 
                    string aid, 
                    string applabel, 
                    object userState) {
            if ((this.compraCE10OperationCompleted == null)) {
                this.compraCE10OperationCompleted = new System.Threading.SendOrPostCallback(this.OncompraCE10OperationCompleted);
            }
            this.InvokeAsync("compraCE10", new object[] {
                        s_transm,
                        c_referencia,
                        val_1,
                        t_servicio,
                        c_cur,
                        t_importe,
                        tarjetahabiente,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        val_11,
                        val_12,
                        clave_entidad,
                        val_16,
                        val_17,
                        val_18,
                        val_19,
                        val_20,
                        email_admin,
                        accion,
                        TAG5F34,
                        TAGSEMV,
                        sFlag,
                        TAG9F26,
                        TAG9F27,
                        fallback,
                        terminal,
                        puntos,
                        version,
                        aid,
                        applabel}, this.compraCE10OperationCompleted, userState);
        }
        
        private void OncompraCE10OperationCompleted(object arg) {
            if ((this.compraCE10Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.compraCE10Completed(this, new compraCE10CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", ResponseNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultaCEReturn")]
        public string consultaCE(
                    int val_1, 
                    int val_2, 
                    int val_3, 
                    int val_4, 
                    string val_5, 
                    string val_6, 
                    string val_7, 
                    string val_8, 
                    string val_9, 
                    string val_10, 
                    string val_11, 
                    string val_12, 
                    string val_13, 
                    string val_14, 
                    string val_15, 
                    int fallback, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19) {
            object[] results = this.Invoke("consultaCE", new object[] {
                        val_1,
                        val_2,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        val_7,
                        val_8,
                        val_9,
                        val_10,
                        val_11,
                        val_12,
                        val_13,
                        val_14,
                        val_15,
                        fallback,
                        val_16,
                        val_17,
                        val_18,
                        val_19});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaCEAsync(
                    int val_1, 
                    int val_2, 
                    int val_3, 
                    int val_4, 
                    string val_5, 
                    string val_6, 
                    string val_7, 
                    string val_8, 
                    string val_9, 
                    string val_10, 
                    string val_11, 
                    string val_12, 
                    string val_13, 
                    string val_14, 
                    string val_15, 
                    int fallback, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19) {
            this.consultaCEAsync(val_1, val_2, val_3, val_4, val_5, val_6, val_7, val_8, val_9, val_10, val_11, val_12, val_13, val_14, val_15, fallback, val_16, val_17, val_18, val_19, null);
        }
        
        /// <remarks/>
        public void consultaCEAsync(
                    int val_1, 
                    int val_2, 
                    int val_3, 
                    int val_4, 
                    string val_5, 
                    string val_6, 
                    string val_7, 
                    string val_8, 
                    string val_9, 
                    string val_10, 
                    string val_11, 
                    string val_12, 
                    string val_13, 
                    string val_14, 
                    string val_15, 
                    int fallback, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    object userState) {
            if ((this.consultaCEOperationCompleted == null)) {
                this.consultaCEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaCEOperationCompleted);
            }
            this.InvokeAsync("consultaCE", new object[] {
                        val_1,
                        val_2,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        val_7,
                        val_8,
                        val_9,
                        val_10,
                        val_11,
                        val_12,
                        val_13,
                        val_14,
                        val_15,
                        fallback,
                        val_16,
                        val_17,
                        val_18,
                        val_19}, this.consultaCEOperationCompleted, userState);
        }
        
        private void OnconsultaCEOperationCompleted(object arg) {
            if ((this.consultaCECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaCECompleted(this, new consultaCECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", ResponseNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("cancelacionCEReturn")]
        public string cancelacionCE(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    string cd_autorizacion, 
                    string terminal) {
            object[] results = this.Invoke("cancelacionCE", new object[] {
                        s_transm,
                        c_referencia,
                        val_1,
                        t_servicio,
                        c_cur,
                        t_importe,
                        tarjetahabiente,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        clave_entidad,
                        val_16,
                        val_17,
                        val_18,
                        val_19,
                        val_20,
                        email_admin,
                        accion,
                        TAG5F34,
                        TAGSEMV,
                        sFlag,
                        TAG9F26,
                        TAG9F27,
                        cd_autorizacion,
                        terminal});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cancelacionCEAsync(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    string cd_autorizacion, 
                    string terminal) {
            this.cancelacionCEAsync(s_transm, c_referencia, val_1, t_servicio, c_cur, t_importe, tarjetahabiente, val_3, val_4, val_5, val_6, clave_entidad, val_16, val_17, val_18, val_19, val_20, email_admin, accion, TAG5F34, TAGSEMV, sFlag, TAG9F26, TAG9F27, cd_autorizacion, terminal, null);
        }
        
        /// <remarks/>
        public void cancelacionCEAsync(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    string cd_autorizacion, 
                    string terminal, 
                    object userState) {
            if ((this.cancelacionCEOperationCompleted == null)) {
                this.cancelacionCEOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelacionCEOperationCompleted);
            }
            this.InvokeAsync("cancelacionCE", new object[] {
                        s_transm,
                        c_referencia,
                        val_1,
                        t_servicio,
                        c_cur,
                        t_importe,
                        tarjetahabiente,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        clave_entidad,
                        val_16,
                        val_17,
                        val_18,
                        val_19,
                        val_20,
                        email_admin,
                        accion,
                        TAG5F34,
                        TAGSEMV,
                        sFlag,
                        TAG9F26,
                        TAG9F27,
                        cd_autorizacion,
                        terminal}, this.cancelacionCEOperationCompleted, userState);
        }
        
        private void OncancelacionCEOperationCompleted(object arg) {
            if ((this.cancelacionCECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelacionCECompleted(this, new cancelacionCECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", ResponseNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("cancelacionCEVReturn")]
        public string cancelacionCEV(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    string cd_autorizacion, 
                    string terminal, 
                    string version) {
            object[] results = this.Invoke("cancelacionCEV", new object[] {
                        s_transm,
                        c_referencia,
                        val_1,
                        t_servicio,
                        c_cur,
                        t_importe,
                        tarjetahabiente,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        clave_entidad,
                        val_16,
                        val_17,
                        val_18,
                        val_19,
                        val_20,
                        email_admin,
                        accion,
                        TAG5F34,
                        TAGSEMV,
                        sFlag,
                        TAG9F26,
                        TAG9F27,
                        cd_autorizacion,
                        terminal,
                        version});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cancelacionCEVAsync(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    string cd_autorizacion, 
                    string terminal, 
                    string version) {
            this.cancelacionCEVAsync(s_transm, c_referencia, val_1, t_servicio, c_cur, t_importe, tarjetahabiente, val_3, val_4, val_5, val_6, clave_entidad, val_16, val_17, val_18, val_19, val_20, email_admin, accion, TAG5F34, TAGSEMV, sFlag, TAG9F26, TAG9F27, cd_autorizacion, terminal, version, null);
        }
        
        /// <remarks/>
        public void cancelacionCEVAsync(
                    string s_transm, 
                    string c_referencia, 
                    int val_1, 
                    string t_servicio, 
                    int c_cur, 
                    string t_importe, 
                    string tarjetahabiente, 
                    string val_3, 
                    string val_4, 
                    string val_5, 
                    string val_6, 
                    int clave_entidad, 
                    string val_16, 
                    string val_17, 
                    string val_18, 
                    string val_19, 
                    string val_20, 
                    string email_admin, 
                    string accion, 
                    string TAG5F34, 
                    string TAGSEMV, 
                    string sFlag, 
                    string TAG9F26, 
                    string TAG9F27, 
                    string cd_autorizacion, 
                    string terminal, 
                    string version, 
                    object userState) {
            if ((this.cancelacionCEVOperationCompleted == null)) {
                this.cancelacionCEVOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelacionCEVOperationCompleted);
            }
            this.InvokeAsync("cancelacionCEV", new object[] {
                        s_transm,
                        c_referencia,
                        val_1,
                        t_servicio,
                        c_cur,
                        t_importe,
                        tarjetahabiente,
                        val_3,
                        val_4,
                        val_5,
                        val_6,
                        clave_entidad,
                        val_16,
                        val_17,
                        val_18,
                        val_19,
                        val_20,
                        email_admin,
                        accion,
                        TAG5F34,
                        TAGSEMV,
                        sFlag,
                        TAG9F26,
                        TAG9F27,
                        cd_autorizacion,
                        terminal,
                        version}, this.cancelacionCEVOperationCompleted, userState);
        }
        
        private void OncancelacionCEVOperationCompleted(object arg) {
            if ((this.cancelacionCEVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelacionCEVCompleted(this, new cancelacionCEVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", ResponseNamespace="http://ws.puntos.cifrada.interred.adquira.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getBinesDeLealtadReturn")]
        public string getBinesDeLealtad(string mail, string accion) {
            object[] results = this.Invoke("getBinesDeLealtad", new object[] {
                        mail,
                        accion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBinesDeLealtadAsync(string mail, string accion) {
            this.getBinesDeLealtadAsync(mail, accion, null);
        }
        
        /// <remarks/>
        public void getBinesDeLealtadAsync(string mail, string accion, object userState) {
            if ((this.getBinesDeLealtadOperationCompleted == null)) {
                this.getBinesDeLealtadOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBinesDeLealtadOperationCompleted);
            }
            this.InvokeAsync("getBinesDeLealtad", new object[] {
                        mail,
                        accion}, this.getBinesDeLealtadOperationCompleted, userState);
        }
        
        private void OngetBinesDeLealtadOperationCompleted(object arg) {
            if ((this.getBinesDeLealtadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBinesDeLealtadCompleted(this, new getBinesDeLealtadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void consultaCompletedEventHandler(object sender, consultaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void compraCompletedEventHandler(object sender, compraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class compraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal compraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void cancelacionCompletedEventHandler(object sender, cancelacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void validaCompletedEventHandler(object sender, validaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void compraCECompletedEventHandler(object sender, compraCECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class compraCECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal compraCECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void compraCEVCompletedEventHandler(object sender, compraCEVCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class compraCEVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal compraCEVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void compraCE10CompletedEventHandler(object sender, compraCE10CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class compraCE10CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal compraCE10CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void consultaCECompletedEventHandler(object sender, consultaCECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaCECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaCECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void cancelacionCECompletedEventHandler(object sender, cancelacionCECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelacionCECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelacionCECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void cancelacionCEVCompletedEventHandler(object sender, cancelacionCEVCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelacionCEVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelacionCEVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getBinesDeLealtadCompletedEventHandler(object sender, getBinesDeLealtadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBinesDeLealtadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBinesDeLealtadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591