//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multipagos2V10.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:8443/InterredWS/services/ProcesadorPagosFullService/")]
        public string Multipagos2V10_ServiciosWebMultipagosInterred3_4_ProcesadorPagosFull {
            get {
                return ((string)(this["Multipagos2V10_ServiciosWebMultipagosInterred3_4_ProcesadorPagosFull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:8443/InterredWS/services/ProcesaDevolucionesFull")]
        public string Multipagos2V10_ServiciosWebMultipagosInterredDevolucion5_1_ProcesaDevolucionesFull {
            get {
                return ((string)(this["Multipagos2V10_ServiciosWebMultipagosInterredDevolucion5_1_ProcesaDevolucionesFul" +
                    "l"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:8443/InterredWS/services/ProcesadorPuntosFull")]
        public string Multipagos2V10_ServiciosWebMultipagosPuntos5_1_ProcesadorPuntosFull {
            get {
                return ((string)(this["Multipagos2V10_ServiciosWebMultipagosPuntos5_1_ProcesadorPuntosFull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9080/MultipagosWS/services/insPagoAmex/")]
        public string Multipagos2V10_ServicioWebMultipagosAmex_AmericanExpressService {
            get {
                return ((string)(this["Multipagos2V10_ServicioWebMultipagosAmex_AmericanExpressService"]));
            }
        }
    }
}
